name: virtual_makeup
channels:
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - mediapipe==0.10.14
      - opencv-contrib-python==4.9.0.80
      - numpy==1.26.4
      - pyside6==6.11.2
