name: virtual_makeup
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.11.9
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - attrs==23.2.0
      - cffi==1.16.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.52.4
      - jax==0.4.28
      - jaxlib==0.4.28
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - mediapipe==0.10.14
      - ml-dtypes==0.4.0
      - numpy==1.26.4
      - opencv-contrib-python==4.9.0.80
      - opt-einsum==3.3.0
      - packaging==24.0
      - pillow==10.3.0
      - protobuf==4.25.3
      - pycparser==2.22
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - scipy==1.13.1
      - six==1.16.0
      - sounddevice==0.4.7
